---
- name: create directory 
  become: true
  file: 
    path: /home/ubuntu/backend
    state: directory
    mode: 0755

- name: Copy compressed backend folder
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu

- name: Run the web server
  become: yes
  shell:
    cmd: |
      cd /home/ubuntu/backend
      npm install
      pm2 stop backend
      pm2 delete backend
      pm2 start npm -- start