- name: Create directory
  become: yes
  file:
    path: /home/ubuntu/backend
    state: directory
- name: Copy compressed backend folder
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend
    owner: ubuntu
   
- name: run web server
  become: yes
  shell:
    cmd: |
      cd /home/ubuntu/backend
      npm install
      pm2 stop default
      pm2 start npm -- start