global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAUHQADVFRPMXD5W25
        secret_key: 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
        port: 9100
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-54-226-122-13.compute-1.amazonaws.com:9100']


global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['ec2-54-226-122-13.compute-1.amazonaws.com:9100']